---
SOMEKEY: Some Other Value
PLUGINS:
  - libmarvin.intents.nullplugin
  - libmarvin.intents.helloplugin
  - libmarvin.intents.helpplugin
  - libmarvin.intents.discordplugin
  - libmarvin.intents.pizzaplugin